# Generated by Django 5.0 on 2023-12-29 09:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z]{2}$', 'Country code consists of 2 capital letters.')])),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Za-z]*$', 'Country name can only contain letters.')])),
            ],
        ),
        migrations.CreateModel(
            name='WineColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[A-Za-z]*$', 'Product type can only contain letters and a frontslash.')])),
            ],
        ),
        migrations.CreateModel(
            name='WineTaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taste', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[A-Za-z]*$', 'Product type can only contain letters and a frontslash.')])),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Za-z]*$', 'Product name can only contain letters.')])),
                ('description', models.TextField()),
                ('image_url', models.CharField(max_length=200)),
                ('year', models.PositiveSmallIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('units_in_stock', models.PositiveSmallIntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.country')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.winecolor')),
                ('taste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.winetaste')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='base.wine')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.order')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.wine')),
            ],
        ),
    ]
