# Generated by Django 5.0 on 2023-12-29 09:16

from django.db import migrations

def create_wine_tastes(apps, schema_editor):
    WineTaste = apps.get_model("base", "WineTaste")
    for taste in ["Dry", "Sweet", "Oaked"]:
        WineTaste.objects.create(taste=taste)

def create_wine_colors(apps, schema_editor):
    WineColor = apps.get_model("base", "WineColor")
    for color in ["Red", "White", "Rose", "Gray", "Orange", "Tawny", "Yellow"]:
        WineColor.objects.create(color=color)  

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_country_winecolor_winetaste_order_wine_review_and_more'),
    ]

    operations = [
        migrations.RunPython(create_wine_tastes),
        migrations.RunPython(create_wine_colors),
    ]
