# Generated by Django 5.0 on 2023-12-29 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20231229_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s]*$', 'Country name can only contain letters.')]),
        ),
        migrations.AlterField(
            model_name='wine',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s]*$', 'Product name can only contain letters.')]),
        ),
        migrations.AlterField(
            model_name='winecolor',
            name='color',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s]*$', 'Product type can only contain letters.')]),
        ),
        migrations.AlterField(
            model_name='winetaste',
            name='taste',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s]*$', 'Product type can only contain letters.')]),
        ),
    ]
