# Generated by Django 5.0 on 2023-12-29 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_country_name_alter_wine_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wines', to='base.winecolor'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wines', to='base.country'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='taste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wines', to='base.winetaste'),
        ),
    ]
