# Generated by Django 5.0 on 2023-12-29 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_wine_color_alter_wine_country_alter_wine_taste'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='orderdetails',
            options={'verbose_name_plural': 'Order Details'},
        ),
    ]
